# acessível ao executar o servidor principal através da URL: http://localhost:8888/service-one/default

message=Hello World from GitHub config server

# porta em que o microsserviço one será executado
server.port=8081